#!/usr/bin/env python3
"""
Generates the project footprint in footprints.pretty/ (KiCad 10 format):

  WAGO_2060-452            2-pole SMD spring terminal, WAGO 2060-452/998-404

and simplified 3D models in footprints.3dshapes/ (VRML):

  WAGO_2060-452            the terminal above
  Waveshare_ESP32-H2-Zero  the H2-Zero on its pin headers, origin at the 5V pin, for the carrier
                           board renders

Pad geometry follows the recommended land pattern in the manufacturer's datasheet;
outline, courtyard and markings are drawn from the package dimensions. The 3D models are boxes
built from the datasheet dimensions (terminal) and the product photos (H2-Zero).

    python3 make_footprints.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "footprints.pretty")
OUT3D = os.path.join(HERE, "footprints.3dshapes")


def fmt(v):
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s == "-0" else s


class Footprint:
    def __init__(self, name, descr, tags, jumpers=None):
        self.name, self.descr, self.tags = name, descr, tags
        self.jumpers = jumpers   # pad numbers connected inside the part
        self.items = []
        self.model = None

    def pad(self, num, x, y, w, h, rot=0):
        self.items.append(f'\t(pad "{num}" smd rect (at {fmt(x)} {fmt(y)} {fmt(rot)}) (size {fmt(w)} {fmt(h)}) '
                          f'(layers "F.Cu" "F.Paste" "F.Mask"))')

    def line(self, x1, y1, x2, y2, layer, width):
        self.items.append(f'\t(fp_line (start {fmt(x1)} {fmt(y1)}) (end {fmt(x2)} {fmt(y2)}) '
                          f'(stroke (width {fmt(width)}) (type solid)) (layer "{layer}"))')

    def rect(self, x1, y1, x2, y2, layer, width):
        self.items.append(f'\t(fp_rect (start {fmt(x1)} {fmt(y1)}) (end {fmt(x2)} {fmt(y2)}) '
                          f'(stroke (width {fmt(width)}) (type solid)) (fill no) (layer "{layer}"))')

    def poly(self, pts, layer):
        xy = " ".join(f"(xy {fmt(x)} {fmt(y)})" for x, y in pts)
        self.items.append(f'\t(fp_poly (pts {xy}) (stroke (width 0.1) (type solid)) (fill yes) (layer "{layer}"))')

    def text(self, s, x, y, layer, size=0.8):
        self.items.append(f'\t(fp_text user "{s}" (at {fmt(x)} {fmt(y)}) (layer "{layer}") '
                          f'(effects (font (size {fmt(size)} {fmt(size)}) (thickness {fmt(size * 0.15)}))))')

    def write(self, ref_y, value_y):
        head = [
            f'(footprint "{self.name}"',
            '\t(version 20241229)',
            '\t(generator "make_footprints.py")',
            '\t(layer "F.Cu")',
            f'\t(descr "{self.descr}")',
            f'\t(tags "{self.tags}")',
            f'\t(property "Reference" "REF**" (at 0 {fmt(ref_y)} 0) (layer "F.SilkS") '
            '(effects (font (size 1 1) (thickness 0.15))))',
            f'\t(property "Value" "{self.name}" (at 0 {fmt(value_y)} 0) (layer "F.Fab") '
            '(effects (font (size 1 1) (thickness 0.15))))',
            '\t(attr smd)',
        ]
        if self.jumpers:
            # pads connected inside the part: KiCad does not ask for a connection on the board
            head.append('\t(duplicate_pad_numbers_are_jumpers yes)')
            head.append('\t(jumper_pad_groups (' + " ".join(f'"{n}"' for n in self.jumpers) + '))')
        items = list(self.items)
        if self.model:
            items.append(f'\t(model "{self.model}" (offset (xyz 0 0 0)) (scale (xyz 1 1 1)) (rotate (xyz 0 0 0)))')
        with open(os.path.join(OUT, self.name + ".kicad_mod"), "w") as f:
            f.write("\n".join(head + items) + "\n)\n")


def write_vrml(name, boxes):
    """Writes a VRML model from boxes (x1, y1, z1, x2, y2, z2, rgb) in footprint mm coordinates.

    KiCad reads VRML in units of 0.1 inch with y pointing up, so y is mirrored and everything
    scaled by 1/2.54.
    """
    nodes = []
    for x1, y1, z1, x2, y2, z2, rgb in boxes:
        c = [(x1 + x2) / 2, -(y1 + y2) / 2, (z1 + z2) / 2]
        size = [abs(x2 - x1), abs(y2 - y1), abs(z2 - z1)]
        nodes.append(
            f"Transform {{ translation {' '.join(fmt(v / 2.54) for v in c)} children Shape {{\n"
            f"  appearance Appearance {{ material Material {{ diffuseColor {' '.join(fmt(v) for v in rgb)} "
            f"specularColor 0.2 0.2 0.2 shininess 0.3 }} }}\n"
            f"  geometry Box {{ size {' '.join(fmt(v / 2.54) for v in size)} }} }} }}")
    with open(os.path.join(OUT3D, name + ".wrl"), "w") as f:
        f.write("#VRML V2.0 utf8\n# generated by make_footprints.py, simplified outline only\n"
                + "\n".join(nodes) + "\n")


def wago_2060_452():
    fp = Footprint("WAGO_2060-452",
                   "WAGO 2060-452/998-404, 2-pole SMD terminal block for 0.2-0.75 mm2, wire entry towards -x",
                   "WAGO 2060 terminal spring SMD")
    # Each pole has a small pad at the release side and a long pad at the wire entry
    for num, y in (("1", -2.0), ("2", 2.0)):
        fp.pad(num, 4.63, y, 3.5, 2.0)
        fp.pad(num, -4.63, y, 2.0, 6.0, rot=90)
    fp.rect(-7.2, -3.95, 6.3, 3.95, "F.Fab", 0.1)
    fp.text("wire", -5.6, 0, "F.Fab", 0.7)
    fp.line(-7.3, -4.1, 6.4, -4.1, "F.SilkS", 0.12)
    fp.line(-7.3, 4.1, 6.4, 4.1, "F.SilkS", 0.12)
    # Courtyard 0.25 mm around body and pads, except on the release side: there the small pads
    # protrude 0.08 mm beyond the body and the courtyard ends at the body, so a part may sit
    # next to them (copper clearance is still checked by the DRC)
    fp.rect(-7.9, -4.2, 6.3, 4.2, "F.CrtYd", 0.05)
    fp.model = "${KIPRJMOD}/../lib/footprints.3dshapes/WAGO_2060-452.wrl"
    fp.write(-5.2, 5.2)

    # 3D model: body 13.1 x 7.9 x 4.5 mm (datasheet), wire entries on the -x face,
    # push-buttons on top, tinned SMD tabs at the pads
    white, grey, dark, tin = (0.93, 0.93, 0.9), (0.7, 0.7, 0.68), (0.08, 0.08, 0.08), (0.8, 0.8, 0.82)
    boxes = [(-7.0, -3.95, 0.15, 6.1, 3.95, 4.5, white)]
    for y in (-2.0, 2.0):
        boxes += [
            (-7.05, y - 0.75, 1.5, -6.2, y + 0.75, 3.0, dark),      # wire entry
            (-5.6, y - 1.3, 4.5, -2.2, y + 1.3, 4.75, grey),        # push-button
            (-7.4, y - 0.8, 0, -2.0, y + 0.8, 0.15, tin),           # long tab, wire side
            (3.2, y - 0.8, 0, 6.3, y + 0.8, 0.15, tin),             # short tab, release side
        ]
    write_vrml("WAGO_2060-452", boxes)


def h2_zero():
    # Board 18 x 23.5 x 1 mm on the plastic strips of the pin headers (2.5 mm). Module coordinates
    # from its top left corner (USB-C side), shifted so the 5V pin (J6 pin 1) is the origin.
    def box(x1, y1, z1, x2, y2, z2, rgb):
        return (x1 - 1.38, y1 - 1.59, z1, x2 - 1.38, y2 - 1.59, z2, rgb)

    blue, gold, black, steel = (0.1, 0.3, 0.75), (0.85, 0.7, 0.3), (0.08, 0.08, 0.08), (0.6, 0.6, 0.63)
    white, red, yellow, brown = (0.92, 0.92, 0.9), (0.8, 0.12, 0.1), (0.95, 0.8, 0.2), (0.45, 0.3, 0.2)
    z0, z1 = 2.5, 3.5                                   # bottom and top of the module board
    boxes = [box(0, 0, z0, 18, 23.5, z1, blue)]
    for x in (1.38, 16.62):
        boxes.append(box(x - 1.27, 0.32, 0, x + 1.27, 23.18, z0, black))          # header strip
        for i in range(9):
            y = 1.59 + 2.54 * i
            boxes.append(box(x - 0.32, y - 0.32, -1.6, x + 0.32, y + 0.32, z1 + 0.8, gold))   # pin
            boxes.append(box(x - 0.8, y - 0.8, z1, x + 0.8, y + 0.8, z1 + 0.05, gold))        # pad
    boxes += [
        box(4.6, -1.5, z1, 13.4, 7.0, z1 + 3.2, steel),            # USB-C, protrudes 1.5 mm
        box(5.4, -1.55, z1 + 0.6, 12.6, -1.0, z1 + 2.6, black),    # its opening
        box(7.0, 11.4, z1, 11.0, 15.4, z1 + 0.85, black),          # ESP32-H2 (QFN 4 x 4)
        box(2.4, 9.0, z1, 6.4, 11.1, z1 + 1.4, white),             # RST
        box(3.9, 9.5, z1 + 1.4, 4.9, 10.6, z1 + 1.9, black),
        box(10.6, 9.0, z1, 14.6, 11.1, z1 + 1.4, white),           # BOOT
        box(12.1, 9.5, z1 + 1.4, 13.1, 10.6, z1 + 1.9, black),
        box(8.4, 9.2, z1, 9.6, 10.4, z1 + 0.6, white),             # RGB LED (IO8)
        box(12.4, 14.4, z1, 14.2, 17.4, z1 + 1.1, black),          # LDO
        box(4.4, 16.4, z1, 6.2, 18.6, z1 + 0.8, steel),            # crystal
        box(3.6, 11.4, z1, 5.6, 12.2, z1 + 0.5, brown),            # a few passives
        box(10.8, 17.6, z1, 12.6, 18.4, z1 + 0.5, brown),
        box(13.6, 17.6, z1, 15.4, 18.4, z1 + 0.5, brown),
        box(5.6, 21.2, z1, 12.4, 23.2, z1 + 1.0, red),             # ceramic antenna
    ]
    write_vrml("Waveshare_ESP32-H2-Zero", boxes)


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(OUT3D, exist_ok=True)
    wago_2060_452()
    h2_zero()
    print("written:", sorted(os.listdir(OUT)), sorted(os.listdir(OUT3D)))
